{{- if .Values.workspaces.enabled  -}}

apiVersion: v1
kind: Service
metadata:
  labels:
    component: workspace-manager-rest
    {{- include "modelix.labels" . | nindent 4 }}
  name: "{{ include "modelix.fullname" . }}-workspace-manager-rest"
spec:
  type: NodePort
  ports:
    - name: "28105"
      port: 28105
      targetPort: 28105
    - name: "debug"
      port: 5072
      targetPort: 5072
  selector:
    component: workspace-manager-rest
    {{- include "modelix.selectorLabels" . | nindent 4 }}
{{- end -}}
