imageTags:
  db: ""
  instancesManager: ""
  proxy: ""
  wsClient: ""
  wsManager: ""
  wsManagerRest: "2021.1.4-202303151526-SNAPSHOT"
  keycloak: ""
ingress:
  hostname: ""
ingress-nginx:
  enabled: true
keycloak:
  loglevel: "warn"
  debug: true
workspaces:
  enabled: true