imageTags:
  db: ""
  instancesManager: ""
  proxy: ""
  wsClient: ""
  wsManager: ""
  keycloak: ""
ingress:
  hostname: "ops-k13-n01.ops.oce.net"
ingress-nginx:
  enabled: true
keycloak:
  loglevel: "warn"
  debug: true
workspaces:
  enabled: true